### ISSUE TITLE
Cannot install R package on version 4.0.2

### ISSUE THREAD

**Issue by dirkdeslegte** [MCKnaus/causalDML#1]
Dear,

I am not able to install the causalDML package. I am running version 4.0.2 of R. What is the recommended version to run this package?

Thanks in advance!

I receive the following messages:

      ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
      ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
      ld: library not found for -lgfortran
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      make: *** [causalDML.so] Error 1
      ERROR: compilation failed for package ‘causalDML’
      * removing ‘/Users/jd/Library/R/4.0/library/causalDML’
      Error: Failed to install 'causalDML' from GitHub:
        (converted from warning) installation of package ‘/var/folders/49/69tgry_d25v8slf0lzy0gfd80000gn/T//RtmpBnHG22/file3c39269feb63/causalDML_0.1.0.tar.gz’ had non-zero exit status

**Comment by dirkdeslegte** [comment]
Dear,

I tried it now on R version 3.6, however, still I receive an error:

* installing *source* package ‘causalDML’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘causalDML’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/causalDML’
Warning message:
In i.p(...) :
 installation of package ‘/var/folders/q8/gth9b_bj1753c0f9lrtxr6hc0000gn/T//RtmpTuppMz/filecc91c40bc7a/causalDML_0.1.0.tar.gz’ had non-zero exit status`

Any advice that you could provide on this?

Thanks in advance!

**Comment by MCKnaus** [comment]
Hi,

I am not a Mac User but it seems that you are missing compilers. Maybe the two following links help to solve this issue:
https://github.com/fxcoudert/gfortran-for-macOS/releases
https://cran.r-project.org/bin/macosx/tools/

I hope this helps.

**Comment by dirkdeslegte** [comment]
Dear, 

That was indeed very helpful. I was able to install the package. One further question, if I may. When determining the IATEs through (N)DR-Learner, does the output of the function ndr_learner also include a confidence interval for each IATE? I noticed that for the ATE there is an SE as output, but I was wondering whether there is a precision indicator for the IATEs.

Thanks a ton!

**Comment by MCKnaus** [comment]
I am not aware of a paper that discusses inference for the IATEs. Actually there are good reasons to believe that it won't be possible to get valid inference for the IATE function, maybe in special cases. I found the discussion in this paper very insightful in this regard https://arxiv.org/abs/1712.04802. 
I currently think about it in this way. (N)DR-learner predict causal effects using ML methods. We know that inference for ML predictions of standard (observed) outcomes is already hard/impossible. Predicting an unobservable causal effect does not make things easier.
However, inference is possible for the lower dimensional GATEs as is implemented in the function kr_cate and spline_cate of the package.
