### ISSUE TITLE
Error in std::bad_alloc

### ISSUE THREAD

**Issue by hlra** [MCKnaus/causalDML#2]
Thanks for the great work so far! I am trying to run a the DML_aipw method on a large matrix (roughly 4,000,000x30). After a while (about 3 days in my case) the execution stops with "std::bad_alloc" error. Google says this seems to be some error in C++ that might be related to insufficient memory. However, reading the matrix itself uses about 21GB RAM, but 150GB are overall available. Is this still insufficient, and if yes, are there ways to reduce use of memory? Or is this error caused by something else? Cheers!

**Comment by MCKnaus** [comment]
Thanks for using the package. It is hard to tell, but I would guess you are running out of memory in the regression forest. The DML_aipw itself does not use C++. If you want to confirm this, specify `quiet = FALSE` which should indicate at which point the program crashes.
Some more points that could help:

- With so many observations, it is probably enough to set `cf=2`. This should also decrease the memory requirements.

- I guess increasing the minimum leaf size in `create_method` could help to address the issue, but maybe you find some help in the `grf` package documentation or issues.

**Comment by hlra** [comment]
Just to give you an update: Decreasing cf worked for me. I stopped the method after ten days because it was stuck for quite a while in the last cross-validation fold, but the original memory issue was solved by your suggestions. Thanks a lot for the hints!

**Comment by MCKnaus** [comment]
Thanks for sharing!
