### ISSUE TITLE
Compilation error after gfortran, clang, and xcode have been installed

### ISSUE THREAD

**Issue by sageknittel** [MCKnaus/causalDML#3]
Hello.

I've been trying to install "causalDML" and have a compilation error that I can't seem to fix. After reading a previous issue, I have installed Xcode, gfortran, and clang to no avail (verified that they are all installed). I am running OSX Monterey and R 4.2.1. Are there any known issues with Monterey and/or 4.2.1?

Thanks!!!

<I'm an R newbie, I freely admit.>

Here's the key line of code:
install_github(repo="MCKnaus/causalDML", lib="/Library/Frameworks/R.framework/Versions/4.2/Resources/library")

Here's the error:
Downloading GitHub repo MCKnaus/causalDML@HEAD
...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [causalDML.so] Error 1
ERROR: compilation failed for package ‘causalDML’

removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/causalDML’
Warning message:
In i.p(...) :
installation of package ‘/var/folders/4k/p656fvb54fb2pv51_w4pnn_00000gp/T//Rtmp97XAls/file557e530a5bca/causalDML_0.1.0.tar.gz’ had non-zero exit status

**Comment by MCKnaus** [comment]
Sorry for the late response. I am not aware of any particular issues for this combination. Have you tried to install any other package from GitHub? E.g.
https://github.com/susanathey/causalTree
https://github.com/forestry-labs/causalToolbox
https://github.com/xnie/rlearner
Trying to install them should tell you whether this is a general problem or sepcific to the causalDML package.

**Comment by MCKnaus** [comment]
I assume that this problem is either fixed or not relevant anymore.
